### ISSUE TITLE
How did you learn C++ and hacking CS GO on Linux?

### ISSUE THREAD

**Issue by mrtuxblux** [Teklad/csgo-horker#10]
^^^
How can a beginner learn it?

**Comment by w3bn00b** [comment]
firstly, but srsly, [ learncpp.com](learncpp.com)
this helped me a LOT

**Comment by Teklad** [comment]
The way I learned C++?  I found a new budding project on Github years ago and just started writing code for it.  Over time you get an idea of what works and what doesn't.  There's so many libraries and extensions available for C++ that I don't really know all of it, and I doubt anyone really does.

As for learning the basics... I'd put together small examples I found here and there.... modify the code to try and make it do something different, etc.  It's one of those languages where you need to genuinely enjoy learning constantly.

As a suggestion, don't follow tutorials you find for learning C++ to the letter.... That'll just teach you how to do it the way it's presented.  Experiment and try something you think will work.

To this day I still make a lot of mistakes when writing code.  I've always programmed in a very trial-and-error fashion though.

**Comment by mrtuxblux** [comment]
Hello. Can you tell me how i can test hacking games with C++ (changing values and reading values) just to see it working or is that maybe too hard for me when i just know cout and cin and int and that you need to use \#include <iostream>, using namespace std if you dont wanna write many features like std::cout, and int main() with { start and  end}

**Comment by Teklad** [comment]
I don't really recommend trying to write hacks if you aren't fairly familiar with the language you're using.  It also requires a minimal level of reverse engineering if you don't already have the memory addresses, function details, and structure/class layouts you need.

As a side note, I never personally use "using namespace xxx" in any of my code.  The reason for this is it sometimes causes conflicts with other functions, which is a whole different topic all together.

I wouldn't bother learning to program just to write hacks.
