### ISSUE TITLE
Bug: No glow on one CT

### ISSUE THREAD

**Issue by mrtuxblux** [Teklad/csgo-horker#12]
I got a bug on mirage competitive that one CT enemy named "lil pump" without "" had no glow on him but all the other ct had.

**Comment by mrtuxblux** [comment]
The people in my team said he was hacking so could he use anti glow and can it by bypassed with this cheat?

**Comment by Teklad** [comment]
This and #13 are related.... Some kind of weird intermittent offset issue that comes and goes.  I probably need to rework the glow a bit anyways... I'll get this fixed asap

**Comment by Teklad** [comment]
I think I managed to fix this... it's a really hard bug to replicate (it happens randomly).  If it shows back up please feel free to reopen this issue.
