### ISSUE TITLE
Aimbot locking on annoying place

### ISSUE THREAD

**Issue by w3bn00b** [Teklad/csgo-horker#16]
[video](https://www.youtube.com/watch?v=N89ebx8Q7jo)

**Comment by Teklad** [comment]
I found out where this is failing at in the code... it's just a matter of coming up with a way to fix it.  Basically FOV is returned as an absolute number (i.e. never negative)...  This is an issue when a target is directly behind you.  If you do a full 180 while standing in front of a target it will still try to lock on to a target.... that's not really there, lol.

**Comment by mrtuxblux** [comment]
Is the default settings good?

**Comment by mrtuxblux** [comment]
only shoot if he is in fov + it's not over 180?

**Comment by mrtuxblux** [comment]
i mean only have it on then

**Comment by mrtuxblux** [comment]
Can you rewrite the config. I dont understand if aimbot is on constantly, if trigger and aimbot is linked and if trigger can even be turned off.

**Comment by Teklad** [comment]
To turn AimBot off set AimAssist to 0.... to turn Trigger off set Trigger to 0.... they're separated in the code.

**Comment by mrtuxblux** [comment]
Okay but how to set aimbot to mouse1? Its not pointer_button 1.

**Comment by w3bn00b** [comment]
issue solved, thanks
