### ISSUE TITLE
Aimbot Mouse Button

### ISSUE THREAD

**Issue by kazukeno** [Teklad/csgo-horker#18]
Please figure out how to use mouse button 1 and write it in the readme.md or something so people know.

**Comment by d1monch1k** [comment]
relevant

**Comment by mrtuxblux** [comment]
I think that it would be good to tell him that many people would appreaciate to know how to get the mouse button to be the aimbot button

**Comment by d1monch1k** [comment]
now aimbot is hard, lol. I played today

**Comment by w3bn00b** [comment]
he already said he will find signature of inputstate, just wait until he do it,
OR if you can do it you can find signature and PR to this repo...

**Comment by Teklad** [comment]
Somewhat done.... updated the readme to tell you how to do it.  Closing this for now.
