### ISSUE TITLE
Feature request: recoil control

### ISSUE THREAD

**Issue by kusayuzayushko** [Teklad/csgo-horker#22]
Can we have it?

**Comment by w3bn00b** [comment]
i made it
since teklad is inactive for a while, i will working on my fork

**Comment by Teklad** [comment]
Just shoot me a PR if you add a feature.  I still can't get the angle based fov to work properly which is why I haven't accepted yet...

I'm not really inactive... Just working on something new at the moment.  This hack will get a good facelift soon.

**Comment by Teklad** [comment]
Done-ish... Let me know if you run into any issues with it... also merged @w3bn00b's extra aim mode.
