### ISSUE TITLE
Can't do cmake ..

### ISSUE THREAD

**Issue by kazukeno** [Teklad/csgo-horker#26]
**This is my error:**

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/home/mrtuxblux/csgo-horker/src/NVCtrlLib_INCLUDE_DIR
   used as include directory in directory /home/mrtuxblux/csgo-horker/src
NVCtrlLib_LIBRARY
    linked by target "horker" in directory /home/mrtuxblux/csgo-horker/src

-- Configuring incomplete, errors occurred!
See also "/home/mrtuxblux/csgo-horker/build/CMakeFiles/CMakeOutput.log".
See also "/home/mrtuxblux/csgo-horker/build/CMakeFiles/CMakeError.log".

**Comment by kazukeno** [comment]
**Uname -a:** Linux mrtuxblux 4.18.4-arch1-1-ARCH #1 SMP PREEMPT Wed Aug 22 07:33:26 UTC 2018 x86_64 GNU/Linux

**Comment by kazukeno** [comment]
Sorry for tagging again xD

**Comment by kazukeno** [comment]
loginctl show-session 2 -p Type
Type=x11

**Comment by Teklad** [comment]
I can close this issue?
