### ISSUE TITLE
Lubuntu cant do cmake

### ISSUE THREAD

**Issue by kazukeno** [Teklad/csgo-horker#27]
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/home/mrtuxblux/csgo-horker/src/NVCtrlLib_INCLUDE_DIR
   used as include directory in directory /home/mrtuxblux/csgo-horker/src
NVCtrlLib_LIBRARY
    linked by target "horker" in directory /home/mrtuxblux/csgo-horker/src
X11_XTest_LIB (ADVANCED)
    linked by target "horker" in directory /home/mrtuxblux/csgo-horker/src

-- Configuring incomplete, errors occurred!
See also "/home/mrtuxblux/csgo-horker/build/CMakeFiles/CMakeOutput.log".
See also "/home/mrtuxblux/csgo-horker/build/CMakeFiles/CMakeError.log".

**Comment by kazukeno** [comment]
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
X11_XTest_LIB (ADVANCED)
    linked by target "horker" in directory /home/mrtuxblux/csgo-horker/src

-- Configuring incomplete, errors occurred!
See also "/home/mrtuxblux/csgo-horker/build/CMakeFiles/CMakeOutput.log".
See also "/home/mrtuxblux/csgo-horker/build/CMakeFiles/CMakeError.log".

Is the new error

**Comment by kazukeno** [comment]
It was fixed with the dependencies now.

**Comment by kazukeno** [comment]
//CLOSED

**Comment by Teklad** [comment]
Fixed
