### ISSUE TITLE
Feature request: AutoBHOP?

### ISSUE THREAD

**Issue by koutsie** [Teklad/csgo-horker#30]
I mean this is very well possible, i got my current solution but would fit for this hack too :3rd_place_medal:

**Comment by Teklad** [comment]
Auto as in..... full auto toggle mode... or auto as in.... hold your jump key and it bhops for you?  Either/or is really easy to implement.

**Comment by koutsie** [comment]
Hold space to autobhop :D

**Comment by Teklad** [comment]
velocity meter and all the other extra goodies, including ESP and bone matrix, will be part of the overlay.  I'm not sure how but this tiny external appears to be expanding fairly quickly.

**Comment by koutsie** [comment]
Ahaha, you dont say: the best part its that this is a fairly good one too!

**Comment by koutsie** [comment]
https://www.youtube.com/watch?v=V3NWCeRXSPs&feature=youtu.be

;)

**Comment by w3bn00b** [comment]
@koutsie can you make a pr with that?

**Comment by juhssi3** [comment]
Should this be closed now?
