### ISSUE TITLE
Odd error while being on opensuse tumbleweed

### ISSUE THREAD

**Issue by RealBloodman** [Teklad/csgo-horker#46]
For some reason even if I surely have all the dependencies and built it just fine it doesn't run and gives me this error: "Failed to initialize input handling". I tried running it straight from the executable and not from the bash script and it gave me the same error, heck, I even tried to redownload it and rebuild it but no luck. (But it worked great while I was on arch :man_shrugging:)
I'm pretty sure my specs wouldn't matter but I'm trying to be as descriptive as possible.
GPU: Nvidia Geforce GTX 1050TI
CPU: Intel core i5-6600
Kernel version: 4.18.5-1-default

Any help would be greatly appreciated
Cheers.

**Comment by RealBloodman** [comment]
I accidently close this issue btw lol

**Comment by Teklad** [comment]
I personally use Arch myself so never run into odd issues like this.  Curiously, is your default desktop using Wayland rather than Xorg?

**Comment by Teklad** [comment]
Try this as a test from the build directory:
```bash
DISPLAY=:0 sudo ./src/horker
```

**Comment by Teklad** [comment]
Also.... give me the output of:
```bash
echo $DISPLAY
```

from your normal user. :p

**Comment by RealBloodman** [comment]
no I can't use wayland since I have an nvidia card but yeah I'll give the output rn gimme a sec

**Comment by RealBloodman** [comment]
and it's 0

**Comment by koutsie** [comment]
Fix: get arch it will work like a charm :3rd_place_medal: 
lo tho use see if youre using xorg.

**Comment by Teklad** [comment]
@RealBloodman go ahead and pull the latest commit... it **really** sounds like your DISPLAY environment variable isn't getting set.  The latest commit should verify that for me.

**Comment by Teklad** [comment]
For reference:
https://forums.opensuse.org/showthread.php/521018-Can-t-open-GUI-programs-as-root

**Comment by w3bn00b** [comment]
you know, get debian and git gut :D

**Comment by RealBloodman** [comment]
`realbloodman@realbloodman:~/csgo-horker> ./run.sh
Failed to find display!
Failed to initialize input handling.
`
Seems that this didn't work either..

**Comment by RealBloodman** [comment]
@w3bn00b @koutsie Can you actually be somewhat helpful and not be annoying with the "gEt THiS DIStrO" comments, my distro is serving me fine but I'm just having an issue with something small hence why I opened this issue..

**Comment by RealBloodman** [comment]
Oh I'm sorry you said you wanted to confirm it so I did, just read that it wasn't a fix lol I just read "go ahead and pull the latest commit"

**Comment by Teklad** [comment]
Yep... it's failing to find the display... OpenSUSE apparently disables crossover of environment variables by default with sudo.  Give this a shot:
```bash
sudo -E ./src/horker
```

That flag preserves environment variables when you use sudo, which apparently isn't the default for SUSE.

**Comment by Teklad** [comment]
If that doesn't work you'll need to use one of gnomesu, kdesu, or xdg-su to run it.

**Comment by RealBloodman** [comment]
Yup, that did work for me, thanks for being so supportive. Seems like you really care about this project haha keep it going :)

**Comment by Teklad** [comment]
Glad to help.  If you run into anymore problems feel free to open up another issue. :)
