### ISSUE TITLE
Cheat crashes when pressing certain mouse keys

### ISSUE THREAD

**Issue by juhssi3** [Teklad/csgo-horker#53]
I Have 2 additional mouse buttons that I have binded to up and down arrows. Whenever i press any of them the cheat gives this:
"[FGlow] Started
 [FOther] Started
 [FVisual] Started
 [FAim] Started
 [xcb] Unknown request in queue while dequeuing
 [xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
 [xcb] Aborting, sorry about that.
 horker: ../../src/xcb_io.c:165: dequeue_pending_request: Assertion `!xcb_xlib_unknown_req_in_deq' 
 failed. 
 Aborted
 juho@ruoska:~/csgo-horker$ "

Binding both buttons to spacebar didnt help.

**Comment by Teklad** [comment]
I think that should fix it... Its a design flaw that I overlooked when I originally wrote the cheat.  All of these bugs should be fixed in the new release.
