### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by ddjem87** [Teklad/csgo-horker#54]
Hey teklad the last time we chat was about the sig scanning and process names can someone help me to change the process name?

(sorry if its a stupid question)

**Comment by Teklad** [comment]
Curiously, why are you needing to change the process name?  If that's all you need to do just rename the file.

**Comment by ddjem87** [comment]
just to be sure cause i got 5 or 6 acc banned but they were cheating on windows but you know its scary some times :D

**Comment by Teklad** [comment]
Windows is a completely different ball game.  They've got signatures for tons of copy/paste cheats for VAC on there. :P

**Comment by ddjem87** [comment]
i know that already its just a completely new ball for me (linux) :P
