### ISSUE TITLE
This is not an issue well actually it is

### ISSUE THREAD

**Issue by avenxd** [Teklad/csgo-horker#55]
I'm new to this whole hacking thing in CS:GO on linux but I've had past experience with windows.
Anyways when I run the commands to install this hack I get some dependency error which I couldn't resolve so I will need help :) 

sudo apt-get install xorg-dev libxnvctrl-dev cmake build-essential git

build-essential is already the newest version (12.4ubuntu1).
git is already the newest version (1:2.17.1-1ubuntu0.1).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 xorg-dev : Depends: libxfont-dev but it is not going to be installed
            Depends: libxft-dev but it is not going to be installed
            Depends: xserver-xorg-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

Please help

**Comment by ddjem87** [comment]
add me on discord if you want to fix it Djem#1222

**Comment by avenxd** [comment]
I fixed it :P
