### ISSUE TITLE
Recoil Smoother on 64tick

### ISSUE THREAD

**Issue by Menarks** [Teklad/csgo-horker#75]
I was wondering how, or at least if this could be accomplished? I've added stuff like visible check, jump check for the aimbot, multiple bone targeting, but I can't figure out how to make the recoil control a little "smoother" for 64tick servers - it's fine on 128 or localhost.

**Comment by suciuale** [comment]
You're the only one seeing it shaky. If you watch the demo, it looks very legit

**Comment by Menarks** [comment]
Ah yeah I just watched it! Looks nice, thanks for the heads up.

**Comment by Teklad** [comment]
The aiming is actually capped at 64 iterations per second (i.e. ticks).  So long as you don't turn your settings too high it should always look smooth in the demo.  I'll go ahead and close this since it seems to be resolved.
