### ISSUE TITLE
aimbot not working

### ISSUE THREAD

**Issue by suciuale** [Teklad/csgo-horker#94]
the aimbot is just ded :(

**Comment by koutsie** [comment]
dumb the offsets, add em in, recompile and see if it works lol

**Comment by koutsie** [comment]
;3

**Comment by telans** [comment]
> dumb the offsets, add em in, recompile and see if it works lol

Any clues where to start? The patterns seem to be different from what TuxDump uses yet the offsets are the same, I've tried updating them but as expected nothing worked.

I've tried changing the offsets that are different, but still no luck.

Perhaps I should learn a bit more of the basics before trying to fix something I don't really understand.

**Comment by kusayuzayushko** [comment]
New netwars https://pastebin.com/muXtLegx

we probably need to fix the offset for `BoneMatrix` and `BoneDistance` in `master/src/offsets.h`, right?

**Comment by suciuale** [comment]
> New netwars https://pastebin.com/muXtLegx
> 
> we probably need to fix the offset for `BoneMatrix` and `BoneDistance` in `master/src/offsets.h`, right?

i can't really find the right offsets. there are no BoneMatrix or BoneDistance in the link you pasted. lil bit of help pls?

**Comment by Teklad** [comment]
I finally had time to look into this.  Looks like the viewangles signatures has possibly changed a bit.  I'll need to poke around some more to verify.
